### ISSUE TITLE
Analyses on non-OD data (cell counts)

### ISSUE THREAD

**Issue by sergiophyceae** [firasmidani/amiga#22]
Hello,

thanks for writing this program which I find very useful. I was woderig how AMiGA can be adapted to be used with data like this:

Time (h)	Data (Cells)
0	20
24	26
48	28
72	20
96	74
120	68
144	170
168	144
192	170
216	106
240	144
264	108

Thank you,

**Comment by firasmidani** [comment]
There are couple of things to consider here: (1) formatting the data, (2) passing the time interval to `AMiGA`, and (2) and adjusting the algorithm to handle the long time interval and high measurement values. 

(1) Regarding formatting, it's pretty simple. See attached [example.txt](https://github.com/firasmidani/amiga/files/15152842/example.txt). Keep in mind that you to need assign an arbitrary well ID for each sample because otherwise `AMiGA` ignores rows without well IDs. For more information on what's considered a well ID, see "Does AMiGA only process 96-well plates?' in this [documentation page](https://firasmidani.github.io/amiga/doc/organization.html).

(2) `AMiGA` also ignores the time measurements in the text file input. So, you need to tell it the measurement interval using the `--interval` parameter. See below command example. You can also modify the default interval in line 27 of the `libs/config.py` file. Search "interval" in in this [documentation page](https://firasmidani.github.io/amiga/doc/organization.html) for more information. 

(3) Finally, this is the most important adjustment. `AMiGA` was optimized to handle microbial growth data which is typically collected over a short period of ~1-3 days and OD measurements that span ~0-5 units. For measurements that span much longer periods (such as your example) and higher measurement values, the Gaussian Process regression will likely fail to fit your data using its default parameters. So, you will to need modify how the Gaussian Process selects a key hyperparameter. You can do this in line 92 of `libs/config.py`. See issue #14 for explanation of the `initialization_method` parameter. 

Once you address the above points, you can then simply analyze your data with `AMiGA` with an interval of 86,400 seconds (i.e. 24 hours) as follows

`python amiga.py fit -i data/example.txt --interval 86400`

Please try it and confirm that it works for you and returns reasonable results.

**Comment by sergiophyceae** [comment]
Thank you for the very informative answer!

The problem I was facing was that the Gaussian process regression was failing or returning non-sensical values. I have modified config.py by making these changes:

config['initialization_method'] = 'moments-based-proper'
config['variance_smoothing_window'] = 2

And the results now appear to make sense. Are these reasonable changes for the kind of data I have?

Thank you,

**Comment by firasmidani** [comment]
This is reasonable but the second parameter `variance_smoothing_window` is only applicable if you are  using `amiga fit` with the `--fix-noise` parameter. 

To elaborate, GP regression can predict growth over time with a confidence interval. By default, the confidence interval is the same across all time points. However, you can empirically estimate the natural variance in your measurement over time by actually measuring this variance from you data over time, then, feeding this to the GP regression model. This can improve its performance in some cases. To do this, you will need to pass the `--fix-noise` parameter to `AMiGA`. 

Essentially, this parameter can fine-tune the predicted growth by allowing `AMiGA` to modify the confidence interval over time. In growth phases where there is lower OD (e.g., lag phase), there should be lower growth and the confidence interval should also be narrower. See [Supplemental Figure 6D](https://journals.asm.org/doi/suppl/10.1128/msystems.00508-21/suppl_file/msystems.00508-21-sf006.tif) and related text in the AMiGA paper for a visual and references. 

A value of 2 for the `variance_smoothing_window` means that AMiGA will compute the variance based on two timepoints at a time (imagine that AMiGA slides a window over the growth curve such that it only see two adjacent timepoints and measures the variance over them). If you want to use the `--fix-noise` argument and you are including replicate growth curves (so using the `--pool` argument), a value of 2 should be fine. If not and you are modeling only a single growth curve at a time, then I recommend a slightly higher value closer to the default of 6.
