### ISSUE TITLE
Issue with pandas?

### ISSUE THREAD

**Issue by bholt20** [firasmidani/amiga#3]
<img width="720" alt="Screen Shot 2021-03-26 at 10 00 55 AM" src="https://user-images.githubusercontent.com/53009624/112642929-2a9a9600-8e1a-11eb-9ac0-4dd58ddce47f.png">

I'm fairly new to python based programming, so this might be a quick fix, but I continue to get this error during while working through the tutorial from git. A little googling lead me to this thread https://github.com/pandas-dev/pandas/issues/36522

The error arrived when running: python amiga.py -i examples/randomii --only-basic-summary

I installed the requirements.txt and ran into two issues that were quickly resolved by uninstalling and reinstalling numpy and pandas. Python is 3.8.5

**Comment by firasmidani** [comment]
Thanks for bringing this to my attention. You are correct; this seems to be an issue due to a difference in the  behavior of ```pandas.replace()``` based on the installed version of pandas. There are also many known issues with numpy and pandas  that can be simply resolved by reinstallation. 

I have patched the issue. In short, instead of passing a type ```int``` to ```pandas.replace()```, I now pass a dictionary which explicitly defines the replacement values for existing values. The updated code should now be compatible with versions of pandas 0.24 or higher.

By the way, I expect to push a new update to AMiGA over the next 1-2 weeks, with major performance improvements, more thorough documentations, and cleaner command-line interface. 

Don’t hesitate to open more issues or ask questions; I appreciate your feedback.
